version: '3.8'

services:
  pwft:
    image: netplexflix/pwft:latest
    container_name: plex-wrapped-for-tautulli
    restart: unless-stopped
    ports:
      - "2025:2025"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/data
    environment:
      # Your timezone (e.g. Europe/Amsterdam). Used for the nightly cache sync time.
      - TZ=UTC
